### ISSUE TITLE
Droidbox.sh OSError

### ISSUE THREAD

**Issue by GoogleCodeExporter** [itdaniher/droidbox#58]
```
What steps will reproduce the problem?
1. ./startemu.sh Test
2. ./droidbox.sh <apk> in the same terminal


What is the expected output? What do you see instead?

Traceback (most recent call last):
  File "scripts/droidbox.py", line 516, in <module>
    main(sys.argv)
  File "scripts/droidbox.py", line 297, in main
    call(['adb', 'logcat', '-c'])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


What version of the product are you using? On what operating system?

Linux Mint 17

java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)

DroidBox 4.1.1

Android version : adt-bundle-linux-x86_64-20140702

Please provide any additional information below.

thanks you :)

```

Original issue reported on code.google.com by `rem...@gmail.com` on 19 Aug 2014 at 8:17

**Comment by giapnx** [comment]
https://stackoverflow.com/questions/8259322/error-when-trying-to-use-droidbox
